[window]
opacity = 0.90

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.normal]
black   = '#000000'
red     = '#aa0000'
green   = '#00aa00'
yellow  = '#fff500'
blue    = '#0000aa'
magenta = '#aa00aa'
cyan    = '#00aaaa'
white   = '#aaaaaa'

[colors.bright]
black   = '#000000'
red     = '#aa0000'
green   = '#00aa00'
yellow  = '#fff500'
blue    = '#0000aa'
magenta = '#aa00aa'
cyan    = '#00aaaa'
white   = '#aaaaaa'

[colors.selection]
text       = 'CellForeground'
background = '#33ff33'

[colors.cursor]
cursor = '#ffffff'

[font.offset]
x = 0
y = 0

[font]
size = 10.5

[font.normal]
family = "unifont"

[keyboard]
bindings = [
  { key = "C", mods = "Alt", action = "Copy" },
  { key = "V", mods = "Alt", action = "Paste" },
]

[general]
live_config_reload = true
