permit persist :wheel
permit persist setenv { WAYLAND_DISPLAY XDG_RUNTIME_DIR DISPLAY CLIPBOARD } rsod
permit nopass rsod cmd nvim args *
permit nopass rsod cmd swaylock
permit nopass rsod cmd swaymsg
